# Generated by Django 3.1.7 on 2021-04-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Write the title of the news item here', max_length=255, verbose_name='Title')),
                ('text', models.TextField(help_text='Write the title of the news item here', verbose_name='Text')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Date the news was published', verbose_name='Date of publication')),
                ('image', models.ImageField(blank=True, help_text='Select a picture for the news', null=True, upload_to='posts/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts_per_page', models.CharField(choices=[('10', 10), ('20', 20), ('50', 50)], default='10', help_text='Select the number of news on the page', max_length=2, verbose_name='The number of news on the page')),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
