openapi: 3.0.2
info:
  title: 'YaLenta'
  version: '1.0.0'
  description: A simple news feed with the ability to publish a post with a picture.
  contact:
    name: Support
    email: fuodorov1998@gmail.com
    url: https://github.com/fuodorov/yalenta

servers:
  - url: /api/v1/

tags:
  - name: POSTS
    description: News posts
  - name: SETTINGS
    description: Dynamic site settings

paths:
  /posts/:
    get:
      tags:
        - POSTS
      description: Get a list of all news posts items
      responses:
        200:
          description: List of news posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
    post:
      tags:
        - POSTS
      description: Create a new post with the news
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        200:
          description: 'New post with the news'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
  /posts/{id}/:
    get:
      tags:
        - POSTS
      description: Get the post by id
      parameters:
      - name: id
        in: path
        required: true
        description: ID post
        schema:
          type: number
      responses:
        200:
          description: Post
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        400:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
    put:
      tags:
        - POSTS
      description: 'Update the post by id'
      parameters:
      - name: id
        in: path
        required: true
        description: ID post
        schema:
          type: number
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        200:
          description: Post
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        400:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
    patch:
      tags:
        - POSTS
      description: Partial update of the post by id
      parameters:
      - name: id
        in: path
        required: true
        description: ID post
        schema:
          type: number
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        200:
          description: Post
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        400:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
    delete:
      tags:
        - POSTS
      description: Delete the post by id
      parameters:
      - name: id
        in: path
        required: true
        description: ID post
        schema:
          type: number
      responses:
        204:
          description: ''
  /settings/:
    get:
      tags:
        - SETTINGS
      description: Get a list of all site settings
      responses:
        200:
          description: List of site settings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Settings'
    post:
      tags:
        - SETTINGS
      description: Create a new site settings
      parameters: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Settings'
      responses:
        200:
          description: 'New site settings'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Settings'

components:
  schemas:
    Post:
      title: Post
      type: object
      description: Details of the post
      required:
        - title
        - text
      properties:
        id:
          type: integer
          title: ID  post
          readOnly: true
        title:
          type: string
          title: Title post
        text:
          type: string
          title: Text post
        image:
          type: image
          format: jpg
          title: Image post
        pub_date:
          type: string
          format: date-time
          title: Date published
          readOnly: true
    Settings:
      title: Site Settings
      type: object
      description: Details of the site settings
      required:
        - posts_per_page
      properties:
        posts_per_page:
          type: string
          title: Posts per page
          default: '10'
          enum:
            - '10'
            - '20'
            - '50'
    ValidationError:
      title: Validation Error
      type: object
      properties:
        field_name:
          type: array
          items:
            type: string